lr12/config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

  post 'session/create'

  get 'session/destroy'

  resources :users
  #resources :session, only: [:new, :create, :destroy]

  #match '/signup', to: 'users#new', via: 'get'

  #match '/signin', to: 'session#new', via: 'get'

  #match '/signout', to: 'session#destroy', via: 'delete'


  #post 'session/create'
  get 'users/new'

  root to: 'lr8#input'

  get 'lr8/input'

  get 'lr8/output'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

lr12/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true

  before_create :create_remember_token

  def User.new_remember_token
  	SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
  	Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
  	self.remember_token = User.encrypt(User.new_remember_token)
  end
end

lr12/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :require_login

  include SessionHelper

  private

  def require_login
  	unless signed_in?
  		flash[:danger] = 'You should sign in'
  		redirect_to session_new_path
  	end
  end

end

lr12/app/controllers/lr8_controller.rb
class Lr8Controller < ApplicationController
  def input
  end

  def output
    word = params[:word]
    @numbers=Array.new
    count = 0
    if word.to_s.empty?
      @result = :blank #"Заполните пустое поле"
 	  elsif word.to_i == 0 
 	    @result = :nan #"Введите числовое значение"
 	  else
 	    @number = word.to_i
 	    (10**(@number-1)..10**@number - 1).to_a.each do |ii|
 	  	  wanted = ii
 	  	  sum = 0
 	  	  @number.times do
 	  		  sum += (ii % 10)**@number
 	  		  ii /= 10
 	  	  end
 	  	  if wanted == sum
 	  		  @numbers[count] = sum
 	  		  count += 1
 	  	  end
 	  	  @result = @numbers.any? ? :ok : :not_found  #numbers : "Для чисел с #{number} цифрами нет чисел Армстронга"
 	    end
	  end
  end
end

lr12/app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new # sign up
  end

  def create # log in
  	user = User.find_by_username(params[:username])
    if user&.authenticate(params[:password])
      #session[:user_id] = user.id
      sign_in user
      redirect_to root_path
      #redirect_to user
    else
      flash[:danger] = 'Invalid username or password'
      redirect_to session_new_path
      #render 'new'
    end
  end

  def destroy # log out
  	sign_out
  	redirect_to session_new_path
  end
end

lr12/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user }#, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        flash[:success] = 'Welcome'
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

lr12/app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

lr12/app/helpers/lr8_helper.rb
module Lr8Helper
end

lr12/app/helpers/session_helper.rb
module SessionHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user) #?self.current_user = user?
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by_remember_token(remember_token) # если @current_user не определен
  end

  

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

lr12/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", session_destroy_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", session_new_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

lr12/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lr12</title>
    <%= csrf_meta_tags %>

    <link rel = "stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/nav' %>
    
  	<div class = 'container' id = 'main-container'>
    	<%= yield %>
    </div>
    
  </body>
</html>

lr12/app/views/lr8/input.html.erb
<h1>Число Армстронга</h1>
<%= form_tag url_for(controller: 'lr8', action: 'output'), method: 'get' do %>

   <%= label_tag  'Введите число' %>
   <%= text_field_tag :word %>

   <br>

   <%= submit_tag 'Проверить' %>

<% end %>

lr12/app/views/lr8/output.html.erb
<h1>Результат</h1>
<% if @result != :ok%> <%= t "results.#{@result}", :number => @number %>
<%else%>
<style>
	table{ width: 300px;
			border: 2px solid; 
			text-align: center; }
	td{border: 1px solid;}
</style>

<table >
	<tr><th >Номер</th><th >Полученное число</th></tr>
	<%count = 0%>
	<%@numbers.each do |i|%>
		<tr><td ><%=@numbers.index(i) + 1%></td><td><%=i.to_s%></td></tr>
		<%count += 1%>
	<%end%>
</table>
<p><%="Количество чисел Армстронга для чисел с #{@result[0].to_s.length} цифрами(-ой): #{count}"%> </p>


<%end%>
<br/>
<%= link_to "Повторить вычисление", :lr8_input %> 

lr12/app/views/partials/_flash.html.erb
<% flash.each do |message_type, message| %>

    <div class="row">

      <div class="col">

        <div class="alert alert-<%= message_type %> alert-dismissible fade show" role="alert">

          <button type="button" class="close" data-dismiss="alert" aria-label="Close" >
            <span aria-hidden="true">&times;</span>
          </button>

          <%= message.html_safe %>

        </div>

      </div>

    </div>

<% end %>

lr12/app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

    <div class="navbar-nav">

      <a class="nav-item nav-link active" href="<%= root_path %>">Home</a>

      <% if signed_in? %>

        <a class="nav-item nav-link active" href="<%= session_destroy_path %>">Sign out</a>

      <% else %>

        <a class="nav-item nav-link active" href="<%= new_user_path %>">Sign up</a>
        <a class="nav-item nav-link active" href="<%= session_new_path %>">Sign in</a>

      <% end %>

    </div>

  </div>

</nav>