Zachetnaya/config/routes.rb
Rails.application.routes.draw do

  get 'session_controller/login'

  post 'session_controller/create'

  get 'session_controller/logout'

  resources :users

  resources :articles do
    resources :comments
  end

 # get '/edit', to: 'users#edit', as: :edit
  root to:  'articles#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Zachetnaya/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Zachetnaya/app/models/article.rb
class Article < ApplicationRecord

  has_many :comments, dependent: :destroy

  validates :title, presence: true,
            length: { minimum: 5 }
end

Zachetnaya/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

Zachetnaya/app/models/user.rb
class User < ApplicationRecord
  alias_attribute :password_digest, :password_hash
  has_secure_password
  validates_uniqueness_of :email, :password_hash
  validates_presence_of :email, :password_hash
  validates_length_of :email, :within => 5..20
  validates_length_of :password, :in => 5..20


  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end

end

Zachetnaya/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :require_login

  include SessionControllerHelper

  private

  def require_login
    unless signed_in?
      flash[:alert] = "Вы должны войти"
      redirect_to session_controller_login_path
    end
end

end

Zachetnaya/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

end

Zachetnaya/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

Zachetnaya/app/controllers/session_controller_controller.rb
class SessionControllerController < ApplicationController
  skip_before_action :require_login, only: [:login, :create]

  def login; end

  def create
    user = User.find_by_email(params[:email])

    if user&.authenticate(params[:password])
      sign_in user
      redirect_to root_path
    else
      flash[:alert] = "Неверный логин или пароль."
      redirect_to session_controller_login_path
    end
  end

  def logout
    cookies.permanent[:remember_token] = nil
    redirect_to session_controller_login_path
  end

  def welcome
  end
end

Zachetnaya/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

Zachetnaya/app/helpers/application_helper.rb
module ApplicationHelper
end

Zachetnaya/app/helpers/articles_helper.rb
module ArticlesHelper
end

Zachetnaya/app/helpers/comments_helper.rb
module CommentsHelper
end

Zachetnaya/app/helpers/session_controller_helper.rb
module SessionControllerHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by_remember_token(remember_token)
  end
end

Zachetnaya/app/helpers/users_helper.rb
module UsersHelper
end

Zachetnaya/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

Zachetnaya/app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>

Zachetnaya/app/views/partials/_flash.html.erb
<% flash.each do |message_type, message| %>

    <div class="row">

      <div class="col">

        <div class="alert alert-<%= message_type %> alert-dismissible fade show" role="alert">


          <%= message.html_safe %>

        </div>

      </div>

    </div>

<% end %>

Zachetnaya/app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

    <div class="navbar-nav">

      <a class="nav-item nav-link active" href="<%= root_path %>">Main</a>

      <% if signed_in? %>

          <a class="nav-item nav-link active" href="<%= users_path %>">All users</a>
          <a class="nav-item nav-link active" href="<%= session_controller_logout_path %>">Exit</a>


      <% else %>

          <a class="nav-item nav-link active" href="<%= new_user_path %>">Registration</a>
          <a class="nav-item nav-link active" href="<%= session_controller_login_path %>">Log in</a>

      <% end %>

    </div>

  </div>

</nav>

Zachetnaya/app/views/session_controller/login.html.erb
<%= render 'partials/flash' %>

<%= form_tag url_for(controller: :session_controller, action: :create), method: 'post' do %>
    <form class="form-horizontal" role="form">
      <div class="form-group">
        </br></br></br>
    <%= label_tag 'Email' %>
    <%= text_field_tag :email, nil, class: 'form-control'%>
      </br>
    <%= label_tag 'Password' %>
    <%= password_field_tag :password, nil, class: 'form-control' %>
      </div>
      </br></br>
    <%= submit_tag 'Log in',class: 'btn btn-success' %>
    </form>
<% end %>